# Generated by Django 4.2.23 on 2025-07-01 08:12

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Unterweisungstyp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('unterweisung_art', models.CharField(choices=[('video', 'Video'), ('text', 'Text')], default='video', max_length=10)),
                ('video', models.FileField(blank=True, null=True, upload_to='unterweisungsvideos/')),
                ('text_markdown', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WeeklyAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('woche', models.DateField(unique=True)),
                ('passwort', models.CharField(blank=True, max_length=50, null=True)),
                ('prefix', models.CharField(default='Makita', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Teilnehmer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vorname', models.CharField(max_length=100)),
                ('nachname', models.CharField(max_length=100)),
                ('firma', models.CharField(max_length=200)),
                ('besuchsgrund', models.TextField()),
                ('unterschrift_datei', models.ImageField(blank=True, null=True, upload_to='signatures/')),
                ('gueltig_bis', models.DateField(default=datetime.datetime(2026, 7, 1, 8, 12, 42, 826165, tzinfo=datetime.timezone.utc))),
                ('unterweisungstyp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unterweisungen.unterweisungstyp')),
            ],
        ),
        migrations.CreateModel(
            name='QuizFrage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frage', models.TextField()),
                ('unterweisungstyp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unterweisungen.unterweisungstyp')),
            ],
        ),
        migrations.CreateModel(
            name='QuizAntwort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('antwort_text', models.CharField(max_length=200)),
                ('ist_richtig', models.BooleanField(default=False)),
                ('frage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unterweisungen.quizfrage')),
            ],
        ),
        migrations.CreateModel(
            name='CheckEintrag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zeitpunkt', models.DateTimeField(auto_now_add=True)),
                ('aktion', models.CharField(choices=[('ein', 'Einchecken'), ('aus', 'Auschecken')], max_length=10)),
                ('teilnehmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unterweisungen.teilnehmer')),
            ],
        ),
    ]
