# Generated by Django 4.2.23 on 2025-07-01 09:05

import datetime
from django.db import migrations, models
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('unterweisungen', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teilnehmer',
            name='gueltig_bis',
            field=models.DateField(default=datetime.datetime(2026, 7, 1, 9, 5, 30, 185971, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='unterweisungstyp',
            name='text_markdown',
            field=markdownx.models.MarkdownxField(blank=True, null=True),
        ),
    ]
