# Generated by Django 4.2.23 on 2025-07-01 14:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unterweisungen', '0002_alter_teilnehmer_gueltig_bis_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailEinstellungen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('betreff', models.CharField(default='Wöchentliches Zugangspasswort', max_length=200)),
                ('text', models.TextField(default='Das neue Zugangspasswort lautet: {passwort}')),
                ('absender', models.EmailField(default='system@deinefirma.at', max_length=254)),
                ('bcc_empfaenger', models.TextField(default='monitoring@miloit.at', help_text='Kommagetrennte Liste der BCC-Empfänger')),
            ],
        ),
        migrations.AlterField(
            model_name='teilnehmer',
            name='gueltig_bis',
            field=models.DateField(default=datetime.datetime(2026, 7, 1, 14, 31, 8, 824651, tzinfo=datetime.timezone.utc)),
        ),
    ]
