# Generated by Django 4.2.23 on 2025-07-01 14:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unterweisungen', '0003_emaileinstellungen_alter_teilnehmer_gueltig_bis'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailEmpfaenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='EmailEinstellungen',
        ),
        migrations.AlterField(
            model_name='teilnehmer',
            name='gueltig_bis',
            field=models.DateField(default=datetime.datetime(2026, 7, 1, 14, 37, 2, 878836, tzinfo=datetime.timezone.utc)),
        ),
    ]
